#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/wallpaper.jpg
fi

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"
polybar > /dev/null &
nm-applet --indicator & 
